_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.1
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 2
                - 13
                - 55
            "4": 3.11.1
            "5": 0.20.1
            "6": 4.53.0
            "8":
                - 1
                - 3
            "12": 0.20.1
            "13": windows-amd64
